#!/bin/bash

echo "\nIniciando ..."
STARTIME=$(date)

for i in $(seq 1 100)
    do
    echo "\n$i Execução..."
    nmap $1 200.239.72.19 
    sleep 5
done

ENDTIME=$(date)

echo "\nInicio $STARTIME"
echo "\nFim $ENDTIME"

