#!/bin/bash

### BEGIN INIT INFO
# Provides:          Snort
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Snort IDS
### END INIT INFO

INTERFACE=eth1
PIDFILE='/var/log/snort/snort_'$INTERFACE'.pid'

start_u2json() {
	PID=$(pgrep idstools-u2json)
	if [ -z $PID ];
	then
		echo "Starting u2json ..."
		su - snort -c "idstools-u2json @/etc/snort/u2json.conf &"
		echo "Service u2json started"
	fi
}

stop_u2json() {
	PID=$(pgrep idstools-u2json)
	if [ -n $PID ];
	then
		echo "Stopping u2json ..."
		kill -15 "$PID"		
	fi
}

start() {
  if [ -s $PIDFILE ]; then
  	PID=`cat $PIDFILE`
	echo "Snort is already running (PID='$PID')"
  else
	echo 'Starting service ...' >&2
	snort -c /etc/snort/snort.conf -D -i $INTERFACE
  	echo 'Service started' >&2
	start_u2json
  fi
}

stop() {
  if [ -s $PIDFILE ]; then
  	PID=`cat $PIDFILE`
	echo 'Stopping service ...' >&2
	kill -15 $PID
	rm $PIDFILE
	echo 'Service stopped' >&2
	stop_u2json
  else 
	echo "Snort is not running"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 5
    start
    ;;
  *)
    echo "Usage: $0 {start | stop | restart}"
esac
