#!/bin/bash

### BEGIN INIT INFO
# Provides:          Suricata
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Suricata IDS
### END INIT INFO

PIDFILE='/var/run/suricata.pid'
INTERFACE=eth1

start() {
  if [ -s $PIDFILE ]; then
  	PID=`cat $PIDFILE`
	echo "Suricata is already running (PID='$PID')"
  else
	echo 'Starting service…' >&2
        `LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4" suricata -c /etc/suricata/suricata.yaml -i $INTERFACE -D` > /dev/null 2>&1
  	echo 'Service started' >&2
  fi
}

stop() {
  if [ -s $PIDFILE ]; then
  	PID=`cat $PIDFILE`
	echo 'Stopping service…' >&2
	kill -15 $PID
	rm $PIDFILE
	echo 'Service stopped' >&2
  else
	echo "Suricata is not running"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 5
    start
    ;;
  *)
    echo "Usage: $0 {start | stop | restart}"
esac
