#!/bin/bash

### BEGIN INIT INFO
# Provides:          Suricata
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Suricata IDS
### END INIT INFO

start() {
  if [ -s '/var/run/suricata.pid' ]; then
  	PID=`cat /var/run/suricata.pid`
	echo "Suricata is already running (PID='$PID')"
        exit
  fi
	echo 'Starting service…' >&2
        `LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4" suricata -c /etc/suricata/suricata.yaml -i eth1 -D` > /dev/null 2>&1
  	echo 'Service started' >&2
}

stop() {
  if [ -s '/var/run/suricata.pid' ]; then
  	PID=`cat /var/run/suricata.pid`
	echo 'Stopping service…' >&2
	kill -15 $PID
	rm /var/run/suricata.pid
	echo 'Service stopped' >&2
	exit
  fi
	echo "Suricata is not running"
	exit 
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    sleep 5
    start
    ;;
  *)
    echo "Usage: $0 {start <interface>|stop|restart}"
esac
